import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute, RouterLink,RouterLinkActive, RouterModule, RouterOutlet, Routes } from '@angular/router';
import { MaterialModule } from './shared-material-module/material.module';
import * as listMenu from '../assets/index.json';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

// Generated by https://quicktype.io

export interface Nodito {
  name:      string;
  img:       string;
  sub_nodes?: SubNode[];
  path?:    string;
}

export interface SubNode {
  name: string;
  path: string;
  img:  string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, MaterialModule,RouterLink, RouterLinkActive],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent implements OnInit {

  modulos!:Nodito[];
  constructor(private http: HttpClient){

  }
  ngOnInit(): void {

    this.http.get<Nodito[]>('/assets/index.json').subscribe( (res:Nodito[]) => {
      console.log(res);
      this.modulos = res;
/*       res.forEach((r)=> {
        console.log(r.path);

      }) */
    })

  }
  activatedRoute = inject(ActivatedRoute);

  title = 'Contraloría';
  listModulos = [
    {
      nombre: 'Generación Masiva',
      isActive: false,
      path: './masiva',
    },
    {
      nombre: 'Configuración de Plazos de Pago',
      isActive: false,
      path: './config',
    },
  ];



}
