// Generated by https://quicktype.io

export interface AlumnoResponse {
  idPerson:               string;
  idAlumno:               string;
  nombre:                 string;
  abrcarrera:             string;
  costoInsumos:           number;
  correo:                 string;
  idgrado:                string;
  idCampus:               string;
  idProspecto:            null;
  nombreResponsable:      string;
  direccion:              string;
  colonia:                string;
  ciudad:                 string;
  cp:                     string;
  telefono:               string;
  entreCalles:            string;
  responsableColegiatura: string;
  borrado:                string;
}
