export interface CostoPromesaResponse {
  // Generated by https://quicktype.io
  id:          string;
  idOperacion: string;
  costo:       string;
  promesas:    string;
  idAlta:      string;
  idPeriodo:   string;
  borrado:     string;

}
